apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/custom-http-errors: "503"
    nginx.ingress.kubernetes.io/default-backend: default-http-backend
    nginx.ingress.kubernetes.io/enable-cors: "false"
    nginx.ingress.kubernetes.io/limit-rpm: "1800"
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
    nginx.ingress.kubernetes.io/proxy-buffer-size: 64k
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  name: api-boiler-plate-public-test-kfz42-de-service
  namespace: default
spec:
  ingressClassName: nginx-public
  rules:
  - host: qa-2-boiler-plate-api.test-kfz42.de
    http:
      paths:
      - backend:
          service:
            name: boiler-plate
            port:
              number: 80
        path: /v1/api(/|$)(.*)
        pathType: ImplementationSpecific
